---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages/blog
  label: Blog
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "{blog/**/*}"
  new_doc_ext: md
  templates:
  - blockpage
- type: document
  path: src/data/menu.json
  label: Menu
- type: document
  path: site-config.json
  label: Settings
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_HOT_LOADER=fast-refresh
  - PATH_PREFIX=/
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
